// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.example.grpc;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string receiver = 2;</code>
   */
  java.lang.String getReceiver();
  /**
   * <code>string receiver = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
